/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankteller;

/**
 *
 * @author student
 */
public class BankTellerApp extends javax.swing.JFrame {

    /**
     * Creates new form BankTellerApp
     */
    public BankTellerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        User = new javax.swing.JPanel();
        NewUser = new javax.swing.JButton();
        EditUser = new javax.swing.JButton();
        QueryUser = new javax.swing.JButton();
        UpdateUser = new javax.swing.JButton();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        LNText = new javax.swing.JTextField();
        PostCode_Label = new javax.swing.JLabel();
        CBB_Label = new javax.swing.JLabel();
        SSB_Field = new javax.swing.JTextField();
        SBB_Label = new javax.swing.JLabel();
        CBB_Field = new javax.swing.JTextField();
        OverDraft_Label = new javax.swing.JLabel();
        overSlider = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        Nation_Label = new javax.swing.JLabel();
        FNText = new javax.swing.JTextField();
        DOB_Label = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        DOBTextField = new javax.swing.JTextField();
        IDField1 = new javax.swing.JTextField();
        NationalityField = new javax.swing.JTextField();
        PostCodeField = new javax.swing.JTextField();
        View = new javax.swing.JPanel();
        ViewPanel = new javax.swing.JScrollPane();
        ViewArea = new javax.swing.JTextArea();
        Display = new javax.swing.JButton();
        AABTN = new javax.swing.JButton();
        Stats = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewStats = new javax.swing.JTextArea();
        HighestSaveBTN = new javax.swing.JButton();
        LowestSaveBTN = new javax.swing.JButton();
        HighestCurBTN = new javax.swing.JButton();
        LowestCurBTN = new javax.swing.JButton();
        Help = new javax.swing.JPanel();
        UserTab_Label = new javax.swing.JLabel();
        Form_Label = new javax.swing.JLabel();
        StatsLabel = new javax.swing.JLabel();
        NotFoundBTN = new javax.swing.JButton();
        AddTutBTN = new javax.swing.JButton();
        UpdateUserBTN = new javax.swing.JButton();
        EditUserBTN = new javax.swing.JButton();
        QueryUserBTN = new javax.swing.JButton();
        FindIDBTN = new javax.swing.JButton();
        Discretion = new javax.swing.JButton();
        FormBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        User.setBackground(new java.awt.Color(255, 51, 51));
        User.setForeground(new java.awt.Color(255, 51, 51));

        NewUser.setText("New User");
        NewUser.setToolTipText("Used to create new Accounts ");
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });

        EditUser.setText("Edit User");
        EditUser.setToolTipText("Allows to edit accounts ");
        EditUser.setPreferredSize(new java.awt.Dimension(100, 23));
        EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserActionPerformed(evt);
            }
        });

        QueryUser.setText("Query User");
        QueryUser.setToolTipText("Search for customer");
        QueryUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryUserActionPerformed(evt);
            }
        });

        UpdateUser.setText("Update User");
        UpdateUser.setToolTipText("Used to update a members balance status");
        UpdateUser.setPreferredSize(new java.awt.Dimension(100, 23));
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        FirstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        FirstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLabel.setText("First Name");

        LastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setText("Last Name");

        LNText.setToolTipText("Enter the accounts last name ");

        PostCode_Label.setBackground(new java.awt.Color(255, 255, 255));
        PostCode_Label.setForeground(new java.awt.Color(255, 255, 255));
        PostCode_Label.setText("Post Code");

        CBB_Label.setBackground(new java.awt.Color(255, 255, 255));
        CBB_Label.setForeground(new java.awt.Color(255, 255, 255));
        CBB_Label.setText("Current Bank Balance ");

        SSB_Field.setToolTipText("The Accounts Savings Balance ");

        SBB_Label.setBackground(new java.awt.Color(255, 255, 255));
        SBB_Label.setForeground(new java.awt.Color(255, 255, 255));
        SBB_Label.setText("Savings Bank Balance ");

        CBB_Field.setToolTipText("The Accounts Current Balance ");

        OverDraft_Label.setBackground(new java.awt.Color(255, 255, 255));
        OverDraft_Label.setForeground(new java.awt.Color(255, 255, 255));
        OverDraft_Label.setText("OverDraft");

        overSlider.setMaximum(1000);
        overSlider.setMinimum(100);
        overSlider.setMinorTickSpacing(100);
        overSlider.setPaintLabels(true);
        overSlider.setPaintTicks(true);
        overSlider.setSnapToTicks(true);
        overSlider.setToolTipText("This is used to set the age of the account");

        Nation_Label.setBackground(new java.awt.Color(255, 255, 255));
        Nation_Label.setForeground(new java.awt.Color(255, 255, 255));
        Nation_Label.setText("Nationality");

        FNText.setToolTipText("Enter the accounts last name ");

        DOB_Label.setBackground(new java.awt.Color(255, 255, 255));
        DOB_Label.setForeground(new java.awt.Color(255, 255, 255));
        DOB_Label.setText("Date Of Birth");

        IDLabel.setForeground(new java.awt.Color(255, 255, 255));
        IDLabel.setText("ID");

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(OverDraft_Label)
                        .addGap(61, 61, 61)
                        .addComponent(overSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(CBB_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBB_Field))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(SBB_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SSB_Field))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserLayout.createSequentialGroup()
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nation_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FNText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(NationalityField)))
                            .addGroup(UserLayout.createSequentialGroup()
                                .addComponent(NewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLayout.createSequentialGroup()
                                .addComponent(DOB_Label)
                                .addGap(18, 18, 18)
                                .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserLayout.createSequentialGroup()
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PostCode_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LNText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(IDField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PostCodeField))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(UserLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(QueryUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLayout.createSequentialGroup()
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nation_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NationalityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PostCode_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PostCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOB_Label)
                            .addComponent(IDLabel)
                            .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SBB_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSB_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBB_Label)
                    .addComponent(CBB_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OverDraft_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QueryUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("User", User);

        View.setBackground(new java.awt.Color(255, 51, 51));

        ViewArea.setColumns(20);
        ViewArea.setRows(5);
        ViewPanel.setViewportView(ViewArea);

        Display.setBackground(new java.awt.Color(255, 255, 255));
        Display.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Display.setText("Display ");
        Display.setToolTipText("Shows how many people are in the banking system");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        AABTN.setBackground(new java.awt.Color(255, 255, 255));
        AABTN.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        AABTN.setText("Add Accounts");
        AABTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AABTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewLayout = new javax.swing.GroupLayout(View);
        View.setLayout(ViewLayout);
        ViewLayout.setHorizontalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewLayout.createSequentialGroup()
                        .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AABTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addGap(67, 67, 67))))
        );
        ViewLayout.setVerticalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AABTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("View", View);

        Stats.setBackground(new java.awt.Color(255, 51, 51));

        ViewStats.setColumns(20);
        ViewStats.setRows(5);
        jScrollPane2.setViewportView(ViewStats);

        HighestSaveBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        HighestSaveBTN.setText("Highest Savings");
        HighestSaveBTN.setToolTipText("Shows the highest savings account");
        HighestSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighestSaveBTNActionPerformed(evt);
            }
        });

        LowestSaveBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LowestSaveBTN.setText("Lowest Savings");
        LowestSaveBTN.setToolTipText("Shows the account with the least savings");
        LowestSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowestSaveBTNActionPerformed(evt);
            }
        });

        HighestCurBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        HighestCurBTN.setText("Highest Current Account");
        HighestCurBTN.setToolTipText("shows the highest current account");
        HighestCurBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighestCurBTNActionPerformed(evt);
            }
        });

        LowestCurBTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LowestCurBTN.setText("Lowest Current Account");
        LowestCurBTN.setToolTipText("Shows the person with the lowest earnings ");
        LowestCurBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowestCurBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StatsLayout = new javax.swing.GroupLayout(Stats);
        Stats.setLayout(StatsLayout);
        StatsLayout.setHorizontalGroup(
            StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(StatsLayout.createSequentialGroup()
                        .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(HighestCurBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HighestSaveBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LowestSaveBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LowestCurBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        StatsLayout.setVerticalGroup(
            StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HighestSaveBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(LowestSaveBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HighestCurBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LowestCurBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stats", Stats);

        Help.setBackground(new java.awt.Color(255, 51, 51));

        UserTab_Label.setBackground(new java.awt.Color(255, 255, 255));
        UserTab_Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UserTab_Label.setText("User Tab");

        Form_Label.setBackground(new java.awt.Color(255, 255, 255));
        Form_Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Form_Label.setText("Form");

        StatsLabel.setBackground(new java.awt.Color(255, 255, 255));
        StatsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        StatsLabel.setText("Stats");

        NotFoundBTN.setText("Not Found");
        NotFoundBTN.setToolTipText("User Not Found");

        AddTutBTN.setText("Add Account");
        AddTutBTN.setToolTipText("How to add Account");

        UpdateUserBTN.setText("Update User");
        UpdateUserBTN.setToolTipText("To help with update user ");

        EditUserBTN.setText("Edit User");
        EditUserBTN.setToolTipText("To help with edit user");

        QueryUserBTN.setText("Query User ");
        QueryUserBTN.setToolTipText("What does Query User do?");

        FindIDBTN.setText("Find ID");
        FindIDBTN.setToolTipText("How to find a members ID");

        Discretion.setText("Discretion");
        Discretion.setToolTipText("Why Names are not displayed");

        FormBTN.setText("Complaint");

        javax.swing.GroupLayout HelpLayout = new javax.swing.GroupLayout(Help);
        Help.setLayout(HelpLayout);
        HelpLayout.setHorizontalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpLayout.createSequentialGroup()
                        .addComponent(UserTab_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(StatsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Form_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HelpLayout.createSequentialGroup()
                        .addGroup(HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NotFoundBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AddTutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(UpdateUserBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditUserBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(QueryUserBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FindIDBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addComponent(Discretion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(FormBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        HelpLayout.setVerticalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserTab_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Form_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NotFoundBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discretion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddTutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QueryUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FindIDBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", Help);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QueryUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryUserActionPerformed
        BluePrint.Query();
    }//GEN-LAST:event_QueryUserActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        BluePrint.viewAccounts();
    }//GEN-LAST:event_DisplayActionPerformed

    private void AABTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AABTNActionPerformed
       BluePrint.addAccounts();
    }//GEN-LAST:event_AABTNActionPerformed

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
        
        BluePrint.newAccounts(IDField1.getText(), FNText.getText(), LNText.getText(), NationalityField.getText(), PostCodeField.getText(), DOBTextField.getText(), SSB_Field.getText(), CBB_Field.getText(), overSlider.getValue());
    }//GEN-LAST:event_NewUserActionPerformed

    private void EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserActionPerformed
        BluePrint.editStaff();
    }//GEN-LAST:event_EditUserActionPerformed

    private void HighestSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighestSaveBTNActionPerformed
        BluePrint.highestSavings();
    }//GEN-LAST:event_HighestSaveBTNActionPerformed

    private void LowestSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowestSaveBTNActionPerformed
        BluePrint.lowestSavings();
    }//GEN-LAST:event_LowestSaveBTNActionPerformed

    private void HighestCurBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighestCurBTNActionPerformed
        BluePrint.HighestCurrent();
    }//GEN-LAST:event_HighestCurBTNActionPerformed

    private void LowestCurBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowestCurBTNActionPerformed
        BluePrint.lowestCurrent();
    }//GEN-LAST:event_LowestCurBTNActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        BluePrint.update();
    }//GEN-LAST:event_UpdateUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankTellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankTellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankTellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankTellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankTellerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AABTN;
    public static javax.swing.JButton AddTutBTN;
    public static javax.swing.JTextField CBB_Field;
    private javax.swing.JLabel CBB_Label;
    public static javax.swing.JTextField DOBTextField;
    private javax.swing.JLabel DOB_Label;
    public static javax.swing.JButton Discretion;
    private javax.swing.JButton Display;
    private javax.swing.JButton EditUser;
    public static javax.swing.JButton EditUserBTN;
    public static javax.swing.JTextField FNText;
    public static javax.swing.JButton FindIDBTN;
    private javax.swing.JLabel FirstNameLabel;
    public static javax.swing.JButton FormBTN;
    private javax.swing.JLabel Form_Label;
    private javax.swing.JPanel Help;
    private javax.swing.JButton HighestCurBTN;
    private javax.swing.JButton HighestSaveBTN;
    public static javax.swing.JTextField IDField1;
    private javax.swing.JLabel IDLabel;
    public static javax.swing.JTextField LNText;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton LowestCurBTN;
    private javax.swing.JButton LowestSaveBTN;
    private javax.swing.JLabel Nation_Label;
    public static javax.swing.JTextField NationalityField;
    private javax.swing.JButton NewUser;
    public static javax.swing.JButton NotFoundBTN;
    private javax.swing.JLabel OverDraft_Label;
    public static javax.swing.JTextField PostCodeField;
    private javax.swing.JLabel PostCode_Label;
    private javax.swing.JButton QueryUser;
    public static javax.swing.JButton QueryUserBTN;
    private javax.swing.JLabel SBB_Label;
    public static javax.swing.JTextField SSB_Field;
    private javax.swing.JPanel Stats;
    private javax.swing.JLabel StatsLabel;
    private javax.swing.JButton UpdateUser;
    public static javax.swing.JButton UpdateUserBTN;
    private javax.swing.JPanel User;
    private javax.swing.JLabel UserTab_Label;
    private javax.swing.JPanel View;
    public static javax.swing.JTextArea ViewArea;
    public static javax.swing.JScrollPane ViewPanel;
    public static javax.swing.JTextArea ViewStats;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JSlider overSlider;
    // End of variables declaration//GEN-END:variables
}
