/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingarray;

/**
 *
 * @author student
 */
public class formPage extends javax.swing.JFrame {

    /**
     * Creates new form formPage
     */
    public formPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FNLabel = new javax.swing.JLabel();
        IssueLabel = new javax.swing.JLabel();
        LNLabel = new javax.swing.JLabel();
        LastNTextBox = new javax.swing.JTextField();
        ETextBox = new javax.swing.JTextField();
        FirstNTextBox = new javax.swing.JTextField();
        ELabel1 = new javax.swing.JLabel();
        IssueTextBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FNLabel.setText("First Name:");
        getContentPane().add(FNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 172, 52));

        IssueLabel.setText("Complaint/Issue");
        getContentPane().add(IssueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 127, 45));

        LNLabel.setText("Last Name:");
        getContentPane().add(LNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 127, 51));
        getContentPane().add(LastNTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 318, 59));
        getContentPane().add(ETextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 318, 51));
        getContentPane().add(FirstNTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 318, 52));

        ELabel1.setText("Email:");
        getContentPane().add(ELabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 187, 127, 45));

        IssueTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(IssueTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 318, 130));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 120, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\student\\Downloads\\Cool-Blue-Waters-With-Sun-Shining-576x1024.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IssueTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssueTextBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ELabel1;
    private javax.swing.JTextField ETextBox;
    private javax.swing.JLabel FNLabel;
    private javax.swing.JTextField FirstNTextBox;
    private javax.swing.JLabel IssueLabel;
    private javax.swing.JTextField IssueTextBox;
    private javax.swing.JLabel LNLabel;
    private javax.swing.JTextField LastNTextBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
