/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fandv;

import static fandv.BluePrint.url;
import java.awt.event.KeyAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.lang.Math;
/**
 *
 * @author dmoc2
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    
         BluePrint.updateCombo(idBOX);
         BluePrint.updateCombo1(categoryBox);
         BluePrint.updateCombo2(colleagueIDBOX);
         BluePrint.updateCombo3(pDates);
         
         
         
         
         cID.setEditable(false);
         cName.setEditable(false);
         cAddress.setEnabled(false);
         postC.setEnabled(false);
         dobField.setEnabled(false);
         cEmail.setEnabled(false);
         phoneField.setEnabled(false);
         createBTN.setEnabled(false);
         adminClear.setEnabled(false);
         DeleteAdmin.setEnabled(false);
         colleagueIDBOX.setEnabled(false);
         viewStaffArea.setEnabled(false);
         viewStock.setEnabled(false);
         viewStaffBTN.setEnabled(false);
         viewStockBTN.setEnabled(false);
    }
    
    private void Checklogin(){
        
        BluePrint log = new BluePrint();
        boolean loggedIn = log.AdminLogin(adminID.getText(), adminE.getText());
        
        //enables panels if the user is logged in 
        
        colleagueShopStock.setEnabled(loggedIn);
        viewStockBTN.setEnabled(loggedIn);
        admin.setEnabled(loggedIn);
        viewStock.setEnabled(loggedIn);
         cID.setEditable(loggedIn);
         cName.setEditable(loggedIn);
         cAddress.setEnabled(loggedIn);
         postC.setEnabled(loggedIn);
         dobField.setEnabled(loggedIn);
         cEmail.setEnabled(loggedIn);
         phoneField.setEnabled(loggedIn);
         createBTN.setEnabled(loggedIn);
         adminClear.setEnabled(loggedIn);
         DeleteAdmin.setEnabled(loggedIn);
         colleagueIDBOX.setEnabled(loggedIn);
         viewStaffArea.setEnabled(loggedIn);
         viewStaffBTN.setEnabled(loggedIn);
        
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        startProgram = new javax.swing.JPanel();
        loadBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        background_og = new javax.swing.JLabel();
        userTabs = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        createAccount = new javax.swing.JPanel();
        FNField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        FNLabel = new javax.swing.JLabel();
        LNField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        submitBTN = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        customerHome = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewCus = new javax.swing.JTextArea();
        viewCusBTN = new javax.swing.JButton();
        icon4 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        reviewOrder = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        reviewOrderTxt = new javax.swing.JTextArea();
        reviewBTN = new javax.swing.JButton();
        title7 = new javax.swing.JLabel();
        icon5 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        previousTab = new javax.swing.JPanel();
        title10 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        previousTXT = new javax.swing.JTextArea();
        pDates = new javax.swing.JComboBox<>();
        Reorder = new javax.swing.JButton();
        background9 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchStock = new javax.swing.JTextArea();
        categoryLabel = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox<>();
        IDLabel = new javax.swing.JLabel();
        idSearch = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        nameView = new javax.swing.JTextPane();
        priceLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        priceView = new javax.swing.JTextPane();
        qtyLabel = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        buyBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        fnText = new javax.swing.JTextField();
        lnLabel = new javax.swing.JLabel();
        lnText = new javax.swing.JTextField();
        fnLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        streetLineLabel = new javax.swing.JLabel();
        STField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        postCodeLabel = new javax.swing.JLabel();
        postField = new javax.swing.JTextField();
        updateBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        logo1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        cusID = new javax.swing.JLabel();
        idBOX = new javax.swing.JComboBox<>();
        background5 = new javax.swing.JLabel();
        staffTabs = new javax.swing.JPanel();
        adminEdit = new javax.swing.JTabbedPane();
        adminLogin = new javax.swing.JPanel();
        adminIDLabel = new javax.swing.JLabel();
        adminEmailLabel = new javax.swing.JLabel();
        adminID = new javax.swing.JTextField();
        adminE = new javax.swing.JTextField();
        loginBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        colleagueShopStock = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewStock = new javax.swing.JTextArea();
        viewStockBTN = new javax.swing.JButton();
        title8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        background6 = new javax.swing.JLabel();
        adminViewColleagues = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewStaffArea = new javax.swing.JTextArea();
        viewStaffBTN = new javax.swing.JButton();
        title9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        background7 = new javax.swing.JLabel();
        admin = new javax.swing.JPanel();
        title6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();
        colleagueIDBOX = new javax.swing.JComboBox<>();
        nameText = new javax.swing.JLabel();
        cName = new javax.swing.JTextField();
        addressText = new javax.swing.JLabel();
        cAddress = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        emailDisplay = new javax.swing.JLabel();
        cEmail = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        createBTN = new javax.swing.JButton();
        adminClear = new javax.swing.JButton();
        DeleteAdmin = new javax.swing.JButton();
        cID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        postC = new javax.swing.JTextField();
        background8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 0, 0));
        jTabbedPane1.setToolTipText("In order to use staff features please login to a admin account!");
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        startProgram.setLayout(null);

        loadBTN.setBackground(new java.awt.Color(204, 0, 0));
        loadBTN.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        loadBTN.setText("Start Program ");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });
        startProgram.add(loadBTN);
        loadBTN.setBounds(87, 183, 437, 83);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        startProgram.add(jLabel1);
        jLabel1.setBounds(440, 20, 120, 100);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        startProgram.add(jButton1);
        jButton1.setBounds(87, 344, 437, 77);

        title1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("Fruit & Vegetable Shop!");
        startProgram.add(title1);
        title1.setBounds(22, 31, 353, 81);

        background_og.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        startProgram.add(background_og);
        background_og.setBounds(11, 6, 580, 670);

        jTabbedPane1.addTab("Start Program", startProgram);

        jTabbedPane2.setBackground(new java.awt.Color(204, 0, 0));
        jTabbedPane2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        createAccount.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        FNField.setToolTipText("Entering ur firstname is the first step to making an account");
        FNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNFieldActionPerformed(evt);
            }
        });
        FNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FNFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FNFieldKeyTyped(evt);
            }
        });

        emailField.setToolTipText("Entering ur email is the third step to making an account");
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailFieldKeyPressed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");

        FNLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FNLabel.setForeground(new java.awt.Color(255, 255, 255));
        FNLabel.setText("First Name");

        LNField.setToolTipText("Entering ur last name is the second step to making an account");
        LNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LNFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LNFieldKeyTyped(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name");

        submitBTN.setBackground(new java.awt.Color(204, 0, 0));
        submitBTN.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        submitBTN.setText("Submit!");
        submitBTN.setToolTipText("Creates an Account within the database");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N

        title.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Fruit & Vegetable Shop!");

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N

        javax.swing.GroupLayout createAccountLayout = new javax.swing.GroupLayout(createAccount);
        createAccount.setLayout(createAccountLayout);
        createAccountLayout.setHorizontalGroup(
            createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(logo))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(FNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(FNField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(LNField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        createAccountLayout.setVerticalGroup(
            createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(logo)
                .addGap(85, 85, 85)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(createAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createAccountLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(531, 531, 531)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAccountLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Create Account", createAccount);

        viewCus.setColumns(20);
        viewCus.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        viewCus.setRows(5);
        viewCus.setToolTipText("Shows the customers in the database");
        jScrollPane3.setViewportView(viewCus);

        viewCusBTN.setBackground(new java.awt.Color(204, 0, 0));
        viewCusBTN.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        viewCusBTN.setText("VIEW");
        viewCusBTN.setToolTipText("Press this button to see the customers!");
        viewCusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCusBTNActionPerformed(evt);
            }
        });

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N

        title4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title4.setForeground(new java.awt.Color(255, 255, 255));
        title4.setText("Fruit & Vegetable Shop!");

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N

        javax.swing.GroupLayout customerHomeLayout = new javax.swing.GroupLayout(customerHome);
        customerHome.setLayout(customerHomeLayout);
        customerHomeLayout.setHorizontalGroup(
            customerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerHomeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(icon4))
            .addGroup(customerHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(customerHomeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(viewCusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(customerHomeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        customerHomeLayout.setVerticalGroup(
            customerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerHomeLayout.createSequentialGroup()
                .addGroup(customerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerHomeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icon4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(viewCusBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(customerHomeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Customer Home ", customerHome);

        reviewOrder.setLayout(null);

        reviewOrderTxt.setColumns(20);
        reviewOrderTxt.setRows(5);
        reviewOrderTxt.setToolTipText("Shows the current order  you have made");
        jScrollPane5.setViewportView(reviewOrderTxt);

        reviewOrder.add(jScrollPane5);
        jScrollPane5.setBounds(12, 117, 554, 370);

        reviewBTN.setBackground(new java.awt.Color(204, 0, 0));
        reviewBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        reviewBTN.setText("Review Order");
        reviewBTN.setToolTipText("Review the order you have bought!");
        reviewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBTNActionPerformed(evt);
            }
        });
        reviewOrder.add(reviewBTN);
        reviewBTN.setBounds(70, 519, 434, 99);

        title7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title7.setForeground(new java.awt.Color(255, 255, 255));
        title7.setText("Fruit & Vegetable Shop!");
        reviewOrder.add(title7);
        title7.setBounds(12, 18, 353, 81);

        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        reviewOrder.add(icon5);
        icon5.setBounds(446, 0, 120, 99);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        reviewOrder.add(background2);
        background2.setBounds(11, 6, 580, 670);

        jTabbedPane2.addTab("Review Order ", reviewOrder);

        title10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title10.setForeground(new java.awt.Color(255, 255, 255));
        title10.setText("Fruit & Vegetable Shop!");

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N

        previousTXT.setColumns(20);
        previousTXT.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        previousTXT.setRows(5);
        previousTXT.setToolTipText("Allows the user to see their previous orders");
        jScrollPane8.setViewportView(previousTXT);

        pDates.setBackground(new java.awt.Color(204, 255, 255));
        pDates.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        pDates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pDates.setToolTipText("Allows the user to pick a date!");
        pDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDatesActionPerformed(evt);
            }
        });

        Reorder.setBackground(new java.awt.Color(204, 0, 0));
        Reorder.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        Reorder.setText("Reorder!");
        Reorder.setToolTipText("Allows the user to reorder a list of items from a specific date");
        Reorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReorderActionPerformed(evt);
            }
        });

        background9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N

        javax.swing.GroupLayout previousTabLayout = new javax.swing.GroupLayout(previousTab);
        previousTab.setLayout(previousTabLayout);
        previousTabLayout.setHorizontalGroup(
            previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previousTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(previousTabLayout.createSequentialGroup()
                        .addComponent(title10, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo2))
                    .addGroup(previousTabLayout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(previousTabLayout.createSequentialGroup()
                                .addComponent(pDates, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reorder, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(previousTabLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(background9, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        previousTabLayout.setVerticalGroup(
            previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previousTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo2)
                    .addComponent(title10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pDates, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reorder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(previousTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previousTabLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(background9, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane2.addTab("Previous Orders", previousTab);

        searchPanel.setLayout(null);

        searchStock.setColumns(20);
        searchStock.setRows(5);
        jScrollPane4.setViewportView(searchStock);

        searchPanel.add(jScrollPane4);
        jScrollPane4.setBounds(270, 120, 301, 329);

        categoryLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        categoryLabel.setText("Category");
        searchPanel.add(categoryLabel);
        categoryLabel.setBounds(10, 130, 86, 46);

        categoryBox.setBackground(new java.awt.Color(204, 255, 255));
        categoryBox.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryBox.setToolTipText("Allows the user to select what category food they want!");
        categoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBoxActionPerformed(evt);
            }
        });
        searchPanel.add(categoryBox);
        categoryBox.setBounds(120, 130, 136, 46);

        IDLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(255, 255, 255));
        IDLabel.setText("ID : ");
        searchPanel.add(IDLabel);
        IDLabel.setBounds(10, 190, 52, 47);

        idSearch.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        idSearch.setToolTipText("The ID allows the search to happen and IDS are displayed in the text box on the right!");
        idSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idSearchKeyTyped(evt);
            }
        });
        searchPanel.add(idSearch);
        idSearch.setBounds(120, 190, 136, 47);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name : ");
        searchPanel.add(nameLabel);
        nameLabel.setBounds(10, 270, 81, 48);

        nameView.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nameView.setToolTipText("This will be filled when users enters search");
        jScrollPane6.setViewportView(nameView);

        searchPanel.add(jScrollPane6);
        jScrollPane6.setBounds(120, 270, 136, 48);

        priceLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Price :");
        searchPanel.add(priceLabel);
        priceLabel.setBounds(10, 340, 81, 47);

        priceView.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        priceView.setToolTipText("This gives the user the price of the product");
        jScrollPane7.setViewportView(priceView);

        searchPanel.add(jScrollPane7);
        jScrollPane7.setBounds(120, 340, 136, 47);

        qtyLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        qtyLabel.setForeground(new java.awt.Color(255, 255, 255));
        qtyLabel.setText("QTY : ");
        searchPanel.add(qtyLabel);
        qtyLabel.setBounds(10, 420, 81, 42);

        qtyField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        qtyField.setToolTipText("Allows the user to enter how much product they want");
        searchPanel.add(qtyField);
        qtyField.setBounds(120, 420, 136, 42);

        buyBTN.setBackground(new java.awt.Color(204, 0, 0));
        buyBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        buyBTN.setText("Buy");
        buyBTN.setToolTipText("Allows the user to buy the products which can be viewed in review order!");
        buyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBTNActionPerformed(evt);
            }
        });
        searchPanel.add(buyBTN);
        buyBTN.setBounds(360, 530, 120, 47);

        searchBTN.setBackground(new java.awt.Color(204, 0, 0));
        searchBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.setToolTipText("Please use me after entering in a id!");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        searchPanel.add(searchBTN);
        searchBTN.setBounds(100, 530, 123, 47);

        clear.setBackground(new java.awt.Color(204, 0, 0));
        clear.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        clear.setText("Clear");
        clear.setToolTipText("Clears the fields");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        searchPanel.add(clear);
        clear.setBounds(230, 570, 123, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        searchPanel.add(jLabel3);
        jLabel3.setBounds(450, 10, 120, 100);

        title5.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title5.setForeground(new java.awt.Color(255, 255, 255));
        title5.setText("Fruit & Vegetable Shop!");
        searchPanel.add(title5);
        title5.setBounds(10, 20, 353, 81);

        View.setBackground(new java.awt.Color(204, 0, 0));
        View.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        View.setText("View");
        View.setToolTipText("Displays all the products ");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        searchPanel.add(View);
        View.setBounds(230, 500, 123, 47);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        searchPanel.add(background3);
        background3.setBounds(11, 6, 580, 670);

        jTabbedPane2.addTab("Search ", searchPanel);

        updatePanel.setLayout(null);

        EmailLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email");
        updatePanel.add(EmailLabel);
        EmailLabel.setBounds(12, 287, 104, 50);

        fnText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fnText.setToolTipText("Allows the user to edit their first name ");
        fnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnTextActionPerformed(evt);
            }
        });
        fnText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnTextKeyTyped(evt);
            }
        });
        updatePanel.add(fnText);
        fnText.setBounds(117, 220, 136, 49);

        lnLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lnLabel.setForeground(new java.awt.Color(255, 255, 255));
        lnLabel.setText("Last Name");
        updatePanel.add(lnLabel);
        lnLabel.setBounds(271, 219, 99, 48);

        lnText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lnText.setToolTipText("Allows the user to edit their last name ");
        lnText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnTextKeyTyped(evt);
            }
        });
        updatePanel.add(lnText);
        lnText.setBounds(382, 220, 168, 49);

        fnLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        fnLabel.setForeground(new java.awt.Color(255, 255, 255));
        fnLabel.setText("First Name");
        updatePanel.add(fnLabel);
        fnLabel.setBounds(8, 219, 104, 49);

        emailText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        emailText.setToolTipText("Allows the user to edit their email");
        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextKeyPressed(evt);
            }
        });
        updatePanel.add(emailText);
        emailText.setBounds(134, 289, 404, 50);

        streetLineLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        streetLineLabel.setForeground(new java.awt.Color(255, 255, 255));
        streetLineLabel.setText("Street Line");
        updatePanel.add(streetLineLabel);
        streetLineLabel.setBounds(12, 357, 104, 49);

        STField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        STField.setToolTipText("Allows the user to edit their Street Line OR Add it!");
        STField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                STFieldKeyPressed(evt);
            }
        });
        updatePanel.add(STField);
        STField.setBounds(134, 358, 404, 49);

        cityLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityLabel.setText("City");
        updatePanel.add(cityLabel);
        cityLabel.setBounds(12, 429, 92, 39);

        cityField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cityField.setToolTipText("Allows the user to edit their city OR ADD IT!");
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        cityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityFieldKeyTyped(evt);
            }
        });
        updatePanel.add(cityField);
        cityField.setBounds(134, 425, 404, 49);

        postCodeLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        postCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        postCodeLabel.setText("Post Code");
        updatePanel.add(postCodeLabel);
        postCodeLabel.setBounds(12, 492, 104, 50);

        postField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        postField.setToolTipText("Allows the user to edit their PostCode OR ADD IT!");
        postField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                postFieldKeyPressed(evt);
            }
        });
        updatePanel.add(postField);
        postField.setBounds(134, 494, 404, 50);

        updateBTN.setBackground(new java.awt.Color(204, 0, 0));
        updateBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        updateBTN.setText("Update");
        updateBTN.setToolTipText("Allows the user to edit their details or add to it");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });
        updatePanel.add(updateBTN);
        updateBTN.setBounds(12, 562, 147, 50);

        clearBTN.setBackground(new java.awt.Color(204, 0, 0));
        clearBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.setToolTipText("Clears all the fields!");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        updatePanel.add(clearBTN);
        clearBTN.setBounds(212, 562, 152, 50);

        deleteBTN.setBackground(new java.awt.Color(204, 0, 0));
        deleteBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.setToolTipText("Allows the user to delete their Account! ");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        updatePanel.add(deleteBTN);
        deleteBTN.setBounds(419, 562, 147, 50);

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        updatePanel.add(logo1);
        logo1.setBounds(446, 13, 120, 90);

        title2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setText("Fruit & Vegetable Shop!");
        updatePanel.add(title2);
        title2.setBounds(37, 22, 353, 81);

        cusID.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cusID.setForeground(new java.awt.Color(255, 255, 255));
        cusID.setText("ID:");
        updatePanel.add(cusID);
        cusID.setBounds(12, 121, 104, 79);

        idBOX.setBackground(new java.awt.Color(204, 255, 255));
        idBOX.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        idBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idBOX.setToolTipText("List of Customers IDs, Use this to fill the fields!");
        idBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBOXActionPerformed(evt);
            }
        });
        updatePanel.add(idBOX);
        idBOX.setBounds(119, 122, 136, 79);

        background5.setForeground(new java.awt.Color(255, 255, 255));
        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        updatePanel.add(background5);
        background5.setBounds(5, 0, 580, 670);

        jTabbedPane2.addTab("Update Customer Details", updatePanel);

        javax.swing.GroupLayout userTabsLayout = new javax.swing.GroupLayout(userTabs);
        userTabs.setLayout(userTabsLayout);
        userTabsLayout.setHorizontalGroup(
            userTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        userTabsLayout.setVerticalGroup(
            userTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("User", userTabs);

        staffTabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffTabsMouseClicked(evt);
            }
        });

        adminEdit.setBackground(new java.awt.Color(204, 0, 0));
        adminEdit.setToolTipText("In order to use staff features please login to a admin account!");
        adminEdit.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        adminIDLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        adminIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminIDLabel.setText("Email:");

        adminEmailLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        adminEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminEmailLabel.setText("ID: ");

        adminID.setToolTipText("Please Enter A Admins ID Number!");
        adminID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adminIDKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminIDKeyPressed(evt);
            }
        });

        adminE.setToolTipText("Please Enter the email of admin ID you have put in!");
        adminE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminEKeyPressed(evt);
            }
        });

        loginBTN.setBackground(new java.awt.Color(204, 0, 0));
        loginBTN.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        loginBTN.setText("Login");
        loginBTN.setToolTipText("The correct details will allow you to use all the staff features!");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N

        title3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title3.setForeground(new java.awt.Color(255, 255, 255));
        title3.setText("Fruit & Vegetable Shop!");

        background4.setForeground(new java.awt.Color(255, 255, 255));
        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N

        javax.swing.GroupLayout adminLoginLayout = new javax.swing.GroupLayout(adminLogin);
        adminLogin.setLayout(adminLoginLayout);
        adminLoginLayout.setHorizontalGroup(
            adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel2))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(adminID, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(adminIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(adminE, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(adminEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminLoginLayout.setVerticalGroup(
            adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(adminID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminLoginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(adminE, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(adminEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        adminEdit.addTab("Admin Login", adminLogin);

        colleagueShopStock.setLayout(null);

        viewStock.setColumns(20);
        viewStock.setRows(5);
        jScrollPane1.setViewportView(viewStock);

        colleagueShopStock.add(jScrollPane1);
        jScrollPane1.setBounds(12, 117, 603, 359);

        viewStockBTN.setBackground(new java.awt.Color(204, 0, 0));
        viewStockBTN.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        viewStockBTN.setText("View Stock");
        viewStockBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStockBTNActionPerformed(evt);
            }
        });
        colleagueShopStock.add(viewStockBTN);
        viewStockBTN.setBounds(12, 494, 603, 117);

        title8.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title8.setForeground(new java.awt.Color(255, 255, 255));
        title8.setText("Fruit & Vegetable Shop!");
        colleagueShopStock.add(title8);
        title8.setBounds(23, 18, 353, 81);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        colleagueShopStock.add(jLabel6);
        jLabel6.setBounds(483, 0, 120, 99);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        colleagueShopStock.add(background6);
        background6.setBounds(23, 0, 592, 683);

        adminEdit.addTab("Shop Stock", colleagueShopStock);

        adminViewColleagues.setLayout(null);
        viewStaffBTN.setEnabled(false);

        viewStaffArea.setColumns(20);
        viewStaffArea.setRows(5);
        jScrollPane2.setViewportView(viewStaffArea);

        adminViewColleagues.add(jScrollPane2);
        jScrollPane2.setBounds(12, 130, 603, 324);

        viewStaffBTN.setBackground(new java.awt.Color(204, 0, 0));
        viewStaffBTN.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        viewStaffBTN.setText("View Staff");
        viewStaffBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStaffBTNActionPerformed(evt);
            }
        });
        adminViewColleagues.add(viewStaffBTN);
        viewStaffBTN.setBounds(22, 473, 581, 136);

        title9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title9.setForeground(new java.awt.Color(255, 255, 255));
        title9.setText("Fruit & Vegetable Shop!");
        adminViewColleagues.add(title9);
        title9.setBounds(25, 13, 353, 81);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        adminViewColleagues.add(jLabel7);
        jLabel7.setBounds(483, 13, 120, 99);

        background7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        adminViewColleagues.add(background7);
        background7.setBounds(23, 0, 592, 683);

        adminEdit.addTab("View Staff", adminViewColleagues);

        admin.setLayout(null);

        title6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        title6.setForeground(new java.awt.Color(255, 255, 255));
        title6.setText("Fruit & Vegetable Shop!");
        admin.add(title6);
        title6.setBounds(12, 13, 353, 81);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fv-logo.png"))); // NOI18N
        admin.add(jLabel4);
        jLabel4.setBounds(470, 13, 120, 99);

        idText.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        idText.setForeground(new java.awt.Color(255, 255, 255));
        idText.setText("ID: ");
        admin.add(idText);
        idText.setBounds(12, 135, 83, 60);

        colleagueIDBOX.setBackground(new java.awt.Color(204, 255, 255));
        colleagueIDBOX.setEditable(true);
        colleagueIDBOX.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        colleagueIDBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        colleagueIDBOX.setToolTipText("Only used for when deleting accounts");
        colleagueIDBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colleagueIDBOXActionPerformed(evt);
            }
        });
        admin.add(colleagueIDBOX);
        colleagueIDBOX.setBounds(369, 136, 223, 60);

        nameText.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setText("Name: ");
        admin.add(nameText);
        nameText.setBounds(12, 214, 83, 50);

        cName.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cName.setToolTipText("Enter the name of the account you are creating");
        cName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNameKeyTyped(evt);
            }
        });
        admin.add(cName);
        cName.setBounds(113, 214, 479, 50);

        addressText.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        addressText.setForeground(new java.awt.Color(255, 255, 255));
        addressText.setText("Address");
        admin.add(addressText);
        addressText.setBounds(12, 283, 83, 50);

        cAddress.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cAddress.setToolTipText("Enter Address of the member");
        cAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cAddressKeyPressed(evt);
            }
        });
        admin.add(cAddress);
        cAddress.setBounds(113, 283, 203, 50);

        dobLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(255, 255, 255));
        dobLabel.setText("DOB:");
        admin.add(dobLabel);
        dobLabel.setBounds(12, 377, 83, 50);

        dobField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        dobField.setToolTipText("Enter their Date of Birth");
        dobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobFieldActionPerformed(evt);
            }
        });
        dobField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobFieldKeyPressed(evt);
            }
        });
        admin.add(dobField);
        dobField.setBounds(113, 377, 100, 50);

        emailDisplay.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        emailDisplay.setForeground(new java.awt.Color(255, 255, 255));
        emailDisplay.setText("Email");
        admin.add(emailDisplay);
        emailDisplay.setBounds(231, 377, 100, 50);

        cEmail.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cEmail.setToolTipText("Enter their email address to give them payslips");
        cEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cEmailKeyPressed(evt);
            }
        });
        admin.add(cEmail);
        cEmail.setBounds(343, 377, 249, 50);

        phoneLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone #");
        admin.add(phoneLabel);
        phoneLabel.setBounds(12, 445, 83, 60);

        phoneField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        phoneField.setToolTipText("Enter their phone number ");
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneFieldKeyPressed(evt);
            }
        });
        admin.add(phoneField);
        phoneField.setBounds(113, 445, 479, 60);

        createBTN.setBackground(new java.awt.Color(204, 0, 0));
        createBTN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        createBTN.setText("Create");
        createBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBTNActionPerformed(evt);
            }
        });
        admin.add(createBTN);
        createBTN.setBounds(20, 550, 150, 50);

        adminClear.setBackground(new java.awt.Color(204, 0, 0));
        adminClear.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        adminClear.setText("Clear");
        adminClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminClearActionPerformed(evt);
            }
        });
        admin.add(adminClear);
        adminClear.setBounds(227, 556, 150, 50);

        DeleteAdmin.setBackground(new java.awt.Color(204, 0, 0));
        DeleteAdmin.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        DeleteAdmin.setText("Delete");
        DeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAdminActionPerformed(evt);
            }
        });
        admin.add(DeleteAdmin);
        DeleteAdmin.setBounds(442, 556, 150, 50);

        cID.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cID.setToolTipText("Used for making accounts");
        cID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cIDKeyTyped(evt);
            }
        });
        admin.add(cID);
        cID.setBounds(113, 135, 252, 61);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Post Code");
        admin.add(jLabel5);
        jLabel5.setBounds(334, 296, 93, 24);

        postC.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        postC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                postCKeyPressed(evt);
            }
        });
        admin.add(postC);
        postC.setBounds(445, 282, 147, 53);

        background8.setForeground(new java.awt.Color(255, 255, 255));
        background8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/b1.jpg"))); // NOI18N
        admin.add(background8);
        background8.setBounds(11, 6, 590, 670);

        adminEdit.addTab("Create & Delete Staff", admin);

        javax.swing.GroupLayout staffTabsLayout = new javax.swing.GroupLayout(staffTabs);
        staffTabs.setLayout(staffTabsLayout);
        staffTabsLayout.setHorizontalGroup(
            staffTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminEdit)
        );
        staffTabsLayout.setVerticalGroup(
            staffTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Staff", staffTabs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BluePrint.showDB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewStockBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStockBTNActionPerformed
        BluePrint.showStock();
    }//GEN-LAST:event_viewStockBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
       BluePrint.scriptRunner();
       BluePrint.displaySearch();
    }//GEN-LAST:event_loadBTNActionPerformed

    private void viewStaffBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStaffBTNActionPerformed
        BluePrint.viewStaff();
        BluePrint.viewAdmin();
    }//GEN-LAST:event_viewStaffBTNActionPerformed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
                Checklogin();
    }//GEN-LAST:event_loginBTNActionPerformed

    private void createBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBTNActionPerformed
        BluePrint.createColleague();
    }//GEN-LAST:event_createBTNActionPerformed

    private void colleagueIDBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colleagueIDBOXActionPerformed
        BluePrint.fillColleagueDetails();
    }//GEN-LAST:event_colleagueIDBOXActionPerformed

    private void adminClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminClearActionPerformed
       BluePrint.clearColleague();
    }//GEN-LAST:event_adminClearActionPerformed

    private void cIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cIDKeyPressed
         int i = cID.getText().length();
        
       if (i == 5) 
       {
            
           JOptionPane.showMessageDialog(null, "5 is the limit!");
        }
    }//GEN-LAST:event_cIDKeyPressed

    private void cIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cIDKeyTyped
      
            char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
           JOptionPane.showMessageDialog(null, "Numbers Only!");
        }

    }//GEN-LAST:event_cIDKeyTyped

    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyTyped
           char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
           JOptionPane.showMessageDialog(null, "Numbers Only!");
        }
    }//GEN-LAST:event_phoneFieldKeyTyped

    private void phoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyPressed
         int i = cID.getText().length();
        
       if (i == 10) 
       {
            
           JOptionPane.showMessageDialog(null, "10 is the limit!");
        }
    }//GEN-LAST:event_phoneFieldKeyPressed

    private void cNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNameKeyTyped
             char c = evt.getKeyChar();
        
        if(!Character.isLetter(c)){
           evt.consume();
           JOptionPane.showMessageDialog(null, "Letters Only!");
        }
    }//GEN-LAST:event_cNameKeyTyped

    private void cNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNameKeyPressed
            int i = cName.getText().length();
        
       if (i == 15) 
       {
            
           JOptionPane.showMessageDialog(null, "15 is the limit!");
        }
    }//GEN-LAST:event_cNameKeyPressed

    private void cAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cAddressKeyPressed
            int i = cAddress.getText().length();
        
       if (i == 40) 
       {
            
           JOptionPane.showMessageDialog(null, "40 is the limit!");
        }
    }//GEN-LAST:event_cAddressKeyPressed

    private void postCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postCKeyPressed
           int i = postC.getText().length();
        
       if (i == 10) 
       {
            
           JOptionPane.showMessageDialog(null, "10 is the limit!");
        }
    }//GEN-LAST:event_postCKeyPressed

    private void dobFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobFieldKeyPressed
           int i = dobField.getText().length();
        
       if (i == 8) 
       {
            
           JOptionPane.showMessageDialog(null, "8 is the limit!");
        }
    }//GEN-LAST:event_dobFieldKeyPressed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
      
    }//GEN-LAST:event_dobFieldActionPerformed

    private void cEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cEmailKeyPressed
                int i = cEmail.getText().length();
        
        if (i == 35) {
            
            JOptionPane.showMessageDialog(null, "35 is the limit!");
        }
    }//GEN-LAST:event_cEmailKeyPressed

    private void adminEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminEKeyPressed
                int i = adminE.getText().length();
        
        if (i == 35) {
            
            JOptionPane.showMessageDialog(null, "35 is the limit!");
        }
    }//GEN-LAST:event_adminEKeyPressed

    private void adminIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminIDKeyTyped
            char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
           evt.consume();
           JOptionPane.showMessageDialog(null, "Numbers Only!");
        }
    }//GEN-LAST:event_adminIDKeyTyped

    private void adminIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminIDKeyPressed
            int i = adminID.getText().length();
        
       if (i == 5) 
       {
            
           JOptionPane.showMessageDialog(null, "5 is the limit!");
        }
    }//GEN-LAST:event_adminIDKeyPressed

    private void DeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAdminActionPerformed
        BluePrint.deleteColleague();
    }//GEN-LAST:event_DeleteAdminActionPerformed

    private void idBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBOXActionPerformed
        BluePrint.go();
    }//GEN-LAST:event_idBOXActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        BluePrint.deleteCustomer();
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        BluePrint.clearCustomer();
    }//GEN-LAST:event_clearBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        BluePrint.updateCustomer();
    }//GEN-LAST:event_updateBTNActionPerformed

    private void postFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postFieldKeyPressed
        int i = postField.getText().length();

        if (i == 10) {

            JOptionPane.showMessageDialog(null, "10 is the limit!");
        }
    }//GEN-LAST:event_postFieldKeyPressed

    private void cityFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityFieldKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Letters Only!");
        }
    }//GEN-LAST:event_cityFieldKeyTyped

    private void cityFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityFieldKeyPressed
        int i = cityField.getText().length();

        if (i == 85) {

            JOptionPane.showMessageDialog(null, "85 is the limit!");
        }
    }//GEN-LAST:event_cityFieldKeyPressed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void STFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_STFieldKeyPressed
        int i = STField.getText().length();

        if (i == 60) {

            JOptionPane.showMessageDialog(null, "60 is the limit!");
        }
    }//GEN-LAST:event_STFieldKeyPressed

    private void emailTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyPressed
        int i = emailText.getText().length();

        if (i == 35) {

            JOptionPane.showMessageDialog(null, "35 is the limit!");
        }
    }//GEN-LAST:event_emailTextKeyPressed

    private void lnTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnTextKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Letters Only!");
        }
    }//GEN-LAST:event_lnTextKeyTyped

    private void lnTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnTextKeyPressed
        int i = lnText.getText().length();

        if (i == 20) {

            JOptionPane.showMessageDialog(null, "20 is the limit!");
        }
    }//GEN-LAST:event_lnTextKeyPressed

    private void fnTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTextKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Letters Only!");
        }
    }//GEN-LAST:event_fnTextKeyTyped

    private void fnTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTextKeyPressed
        int i = fnText.getText().length();

        if (i == 12) {

            JOptionPane.showMessageDialog(null, "12 is the limit!");
        }

    }//GEN-LAST:event_fnTextKeyPressed

    private void fnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnTextActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        BluePrint.displaySearch();
    }//GEN-LAST:event_ViewActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        idSearch.setText(null);
        nameView.setText(null);
        priceView.setText(null);
        qtyField.setText(null);

    }//GEN-LAST:event_clearActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        BluePrint.searchBTN();
    }//GEN-LAST:event_searchBTNActionPerformed

    private void buyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBTNActionPerformed
        BluePrint.buy();
         //let user know 
    }//GEN-LAST:event_buyBTNActionPerformed

    private void idSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idSearchKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Numbers Only!");
        }
    }//GEN-LAST:event_idSearchKeyTyped

    private void idSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idSearchKeyPressed
        int i = idSearch.getText().length();

        if (i == 5)
        {

            JOptionPane.showMessageDialog(null, "5 is the limit!");
        }
    }//GEN-LAST:event_idSearchKeyPressed

    private void categoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBoxActionPerformed
        BluePrint.displayCertain();
    }//GEN-LAST:event_categoryBoxActionPerformed

    private void reviewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBTNActionPerformed
        BluePrint.reviewBuy();
    }//GEN-LAST:event_reviewBTNActionPerformed

    private void viewCusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCusBTNActionPerformed
        BluePrint.viewCustomer();
    }//GEN-LAST:event_viewCusBTNActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        BluePrint.createCustomer();
    }//GEN-LAST:event_submitBTNActionPerformed

    private void LNFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LNFieldKeyPressed
        int i = LNField.getText().length();

        if (i == 20) {

            JOptionPane.showMessageDialog(null, "20 is the limit!");
        }
    }//GEN-LAST:event_LNFieldKeyPressed

    private void LNFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LNFieldKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Letters Only!");
        }
    }//GEN-LAST:event_LNFieldKeyTyped

    private void emailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyPressed
        int i = emailField.getText().length();

        if (i == 35) {

            JOptionPane.showMessageDialog(null, "35 is the limit!");
        }
    }//GEN-LAST:event_emailFieldKeyPressed

    private void FNFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FNFieldKeyPressed
        int i = FNField.getText().length();

        if (i == 12) {

            JOptionPane.showMessageDialog(null, "12 is the limit!");
        }
    }//GEN-LAST:event_FNFieldKeyPressed

    private void FNFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FNFieldKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Letters Only!");
        }
    }//GEN-LAST:event_FNFieldKeyTyped

    private void FNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNFieldActionPerformed

    private void pDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDatesActionPerformed
        BluePrint.pickPreviousOrder();
    }//GEN-LAST:event_pDatesActionPerformed

    private void ReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReorderActionPerformed
       BluePrint.reorder();
    }//GEN-LAST:event_ReorderActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
      
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void staffTabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffTabsMouseClicked
        JOptionPane.showMessageDialog(null, "In order to use staff features please login to a admin account!"); //let user know 
    }//GEN-LAST:event_staffTabsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteAdmin;
    private javax.swing.JLabel EmailLabel;
    public static javax.swing.JTextField FNField;
    private javax.swing.JLabel FNLabel;
    private javax.swing.JLabel IDLabel;
    public static javax.swing.JTextField LNField;
    private javax.swing.JButton Reorder;
    public static javax.swing.JTextField STField;
    private javax.swing.JButton View;
    private javax.swing.JLabel addressText;
    private javax.swing.JPanel admin;
    private javax.swing.JButton adminClear;
    private javax.swing.JTextField adminE;
    public static javax.swing.JTabbedPane adminEdit;
    private javax.swing.JLabel adminEmailLabel;
    private javax.swing.JTextField adminID;
    private javax.swing.JLabel adminIDLabel;
    private javax.swing.JPanel adminLogin;
    private javax.swing.JPanel adminViewColleagues;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background7;
    private javax.swing.JLabel background8;
    private javax.swing.JLabel background9;
    private javax.swing.JLabel background_og;
    private javax.swing.JButton buyBTN;
    public static javax.swing.JTextField cAddress;
    public static javax.swing.JTextField cEmail;
    public static javax.swing.JTextField cID;
    public static javax.swing.JTextField cName;
    public static javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JLabel categoryLabel;
    public static javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton clear;
    private javax.swing.JButton clearBTN;
    public static javax.swing.JComboBox<String> colleagueIDBOX;
    private javax.swing.JPanel colleagueShopStock;
    private javax.swing.JPanel createAccount;
    private javax.swing.JButton createBTN;
    private javax.swing.JLabel cusID;
    private javax.swing.JPanel customerHome;
    private javax.swing.JButton deleteBTN;
    public static javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailDisplay;
    public static javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    public static javax.swing.JTextField emailText;
    private javax.swing.JLabel fnLabel;
    public static javax.swing.JTextField fnText;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    public static javax.swing.JComboBox<String> idBOX;
    public static javax.swing.JTextField idSearch;
    private javax.swing.JLabel idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lnLabel;
    public static javax.swing.JTextField lnText;
    private javax.swing.JButton loadBTN;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameText;
    public static javax.swing.JTextPane nameView;
    public static javax.swing.JComboBox<String> pDates;
    public static javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    public static javax.swing.JTextField postC;
    private javax.swing.JLabel postCodeLabel;
    public static javax.swing.JTextField postField;
    public static javax.swing.JTextArea previousTXT;
    private javax.swing.JPanel previousTab;
    private javax.swing.JLabel priceLabel;
    public static javax.swing.JTextPane priceView;
    public static javax.swing.JTextField qtyField;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JButton reviewBTN;
    private javax.swing.JPanel reviewOrder;
    public static javax.swing.JTextArea reviewOrderTxt;
    private javax.swing.JButton searchBTN;
    private javax.swing.JPanel searchPanel;
    public static javax.swing.JTextArea searchStock;
    private javax.swing.JPanel staffTabs;
    private javax.swing.JPanel startProgram;
    private javax.swing.JLabel streetLineLabel;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JButton updateBTN;
    public static javax.swing.JPanel updatePanel;
    private javax.swing.JPanel userTabs;
    public static javax.swing.JTextArea viewCus;
    private javax.swing.JButton viewCusBTN;
    public static javax.swing.JTextArea viewStaffArea;
    private javax.swing.JButton viewStaffBTN;
    public static javax.swing.JTextArea viewStock;
    private javax.swing.JButton viewStockBTN;
    // End of variables declaration//GEN-END:variables
}
